{% set name = "openff-forcefields" %}
{% set version = "2025.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openforcefield/openff-forcefields/archive/{{ version }}.tar.gz
  sha256: 1dc121ff5e4f46407a00152cc829df5cdf672c058ea3fc36cd6dd99de46d56c8
 
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools
  run_constrained:
    - openforcefields ==9999999999
test:
  requires:
    - openff-toolkit-base
    - rdkit  # a cheminformatics toolkit is needed for parsing OFFXMLs
    - python {{ python_min }}
  imports:
    - openforcefields
  files:
    - test.py
  commands:
    - python test.py

about:
  home: https://openforcefield.org/
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: Force fields released by the Open Force Field Initiative.
  description: |
    The provided OFFXML (force field) files are successive versions
    of a general-purpose small molecule force field, written in the
    SMIRNOFF format; this force field should cover all or almost all
    of drug-like chemical space, and illustrate some of the major
    functionality of the SMIRNOFF format as well as how it simplifies
    the specification of force field parameters in a compact and
    chemically sensible way.
  doc_url: https://github.com/openforcefield/openff-forcefields
  dev_url: https://github.com/openforcefield/openff-forcefields

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - j-wags
    - mattwthompson
    - simonboothroyd
    - lilyminium
    - amcisaac
